version: '3'
networks:
  webapi:
    driver: bridge
services:
  sqlserver2017:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "0rUOw5M5ad"
    ports:
    - "1433:1433"
    networks:
      - webapi
  desafio-csharp-easy-test:
    ports:
      - "5000:5000"
    image: desafioteste
    build:
      context: ./WebApplication
      dockerfile: Dockerfile
    depends_on:
      - sqlserver2017
    networks:
      - webapi
    command: [ "dotnet", "ef", "database update" ]